"""ORM models for the Third-Party Onboarding Suite."""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Float, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from metadata_architect.database import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _uuid() -> uuid.UUID:
    return uuid.uuid4()


class ColumnDefinition(Base):
    """
    AI-drafted plain-language definition for a single data column.
    Persisted to the Enterprise_Glossary on SME approval.
    """
    __tablename__ = "column_definitions"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=_uuid)
    asset_name: Mapped[str] = mapped_column(String(256), nullable=False, index=True)
    column_name: Mapped[str] = mapped_column(String(256), nullable=False)
    data_type: Mapped[str] = mapped_column(String(64), nullable=False)
    source_system: Mapped[str | None] = mapped_column(String(128), nullable=True)
    business_definition: Mapped[str] = mapped_column(Text, nullable=False)
    plain_name: Mapped[str] = mapped_column(String(256), nullable=False)
    usage_examples: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    warnings: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    readability_grade: Mapped[float] = mapped_column(Float, nullable=False)
    linguistic_compliant: Mapped[bool] = mapped_column(Boolean, default=False)
    # "pending" | "approved" | "edited" | "rejected"
    sme_status: Mapped[str] = mapped_column(String(32), default="pending", nullable=False)
    sme_edited_definition: Mapped[str | None] = mapped_column(Text, nullable=True)
    model_used: Mapped[str] = mapped_column(String(128), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class SecurityPassportRecord(Base):
    """
    Security Passport attached to a data asset.
    Classification badge fed into the Governance Entry Gate.
    """
    __tablename__ = "security_passports"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=_uuid)
    asset_name: Mapped[str] = mapped_column(String(256), nullable=False, index=True)
    # "Public" | "Internal" | "Confidential" | "Restricted"
    classification: Mapped[str] = mapped_column(String(32), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    risk_signals: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    quarantine_recommended: Mapped[bool] = mapped_column(Boolean, default=False)
    quarantine_reason: Mapped[str] = mapped_column(Text, default="")
    remediation_steps: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    regulatory_frameworks: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    payload_fingerprint: Mapped[str] = mapped_column(String(64), nullable=False)
    # "pending_review" | "cleared" | "quarantined"
    gate_status: Mapped[str] = mapped_column(String(32), default="pending_review", nullable=False)
    model_used: Mapped[str] = mapped_column(String(128), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class DataContractRecord(Base):
    """
    ODCS Data Contract generated by the Interview Bot.
    Persisted to the Data_Contract_Registry.
    """
    __tablename__ = "data_contracts"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=_uuid)
    contract_id: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    asset_name: Mapped[str] = mapped_column(String(256), nullable=False, index=True)
    owner: Mapped[str] = mapped_column(String(256), default="")
    soi_category: Mapped[str] = mapped_column(String(64), nullable=False)
    business_decision: Mapped[str] = mapped_column(Text, nullable=False)
    mandatory_fields: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    update_frequency: Mapped[str] = mapped_column(String(64), nullable=False)
    freshness_max_age: Mapped[str] = mapped_column(String(64), nullable=False)
    retention_period: Mapped[str] = mapped_column(String(64), nullable=False)
    availability_sla: Mapped[float] = mapped_column(Float, default=99.9)
    quality_completeness: Mapped[float] = mapped_column(Float, default=0.95)
    schema_hints: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    contract_yaml: Mapped[str] = mapped_column(Text, nullable=False)
    contract_json: Mapped[dict] = mapped_column(JSONB, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    clarification_needed: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    linguistic_compliant: Mapped[bool] = mapped_column(Boolean, default=False)
    # "draft" | "active" | "superseded" | "terminated"
    status: Mapped[str] = mapped_column(String(32), default="draft", nullable=False)
    version: Mapped[str] = mapped_column(String(32), default="1.0.0", nullable=False)
    model_used: Mapped[str] = mapped_column(String(128), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )
    activated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
